export const API_BASE_URL = 'http://localhost:3000';

export const AUTH_ENDPOINTS = { google: '/auth/google', googleCallback: '/auth/google/callback', me: '/auth/me' } as const;
export const PRODUCT_ENDPOINTS = { query: '/products/query', filter: '/products/filter', categories: '/products/categories', all: '/products', deleted: '/products/deleted', create: '/products', getById: (id: number) => `/products/${id}`, update: (id: number) => `/products/${id}`, delete: (id: number) => `/products/${id}`, permanentDelete: (id: number) => `/products/${id}/permanent`, restore: (id: number) => `/products/${id}/restore` } as const;
export const ORDER_ENDPOINTS = { current: '/orders/current', list: '/orders', getById: (id: number) => `/orders/${id}`, create: '/orders', addItem: (orderId: number) => `/orders/${orderId}/items`, getItem: (itemId: number) => `/orders/items/${itemId}`, updateItem: (itemId: number) => `/orders/items/${itemId}`, deleteItem: (itemId: number) => `/orders/items/${itemId}`, complete: (orderId: number) => `/orders/${orderId}/complete` } as const;
export const DISCOUNT_ENDPOINTS = { create: '/discounts', list: '/discounts', deleted: '/discounts/deleted', getById: (id: number) => `/discounts/${id}`, update: (id: number) => `/discounts/${id}`, delete: (id: number) => `/discounts/${id}` } as const;
export const HTTP_METHODS = { GET: 'GET', POST: 'POST', PUT: 'PUT', DELETE: 'DELETE', PATCH: 'PATCH', OPTIONS: 'OPTIONS' } as const;
export const STATUS_CODES = { OK: 200, CREATED: 201, BAD_REQUEST: 400, UNAUTHORIZED: 401, FORBIDDEN: 403, NOT_FOUND: 404, CONFLICT: 409, UNPROCESSABLE_ENTITY: 422, INTERNAL_SERVER_ERROR: 500, SERVICE_UNAVAILABLE: 503 } as const;

export function buildApiUrl(endpoint: string): string { return `${API_BASE_URL}${endpoint}`; }
export function createAuthHeader(token: string): Record<string, string> { return { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }; }
export function createJsonHeader(): Record<string, string> { return { 'Content-Type': 'application/json' }; }
export function buildQueryString(params: Record<string, any>): string { const searchParams = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== null) searchParams.append(key, String(value)); }); const queryString = searchParams.toString(); return queryString ? `?${queryString}` : ''; }
export function buildUrlWithQuery(endpoint: string, params?: Record<string, any>): string { const url = buildApiUrl(endpoint); if (!params || Object.keys(params).length === 0) return url; return url + buildQueryString(params); }

export const ApiRoutes = {
  auth: { google: () => buildApiUrl(AUTH_ENDPOINTS.google), me: () => buildApiUrl(AUTH_ENDPOINTS.me) },
  products: { query: (params?: Record<string, any>) => buildUrlWithQuery(PRODUCT_ENDPOINTS.query, params), filter: () => buildApiUrl(PRODUCT_ENDPOINTS.filter), categories: () => buildApiUrl(PRODUCT_ENDPOINTS.categories), all: () => buildApiUrl(PRODUCT_ENDPOINTS.all), deleted: () => buildApiUrl(PRODUCT_ENDPOINTS.deleted), create: () => buildApiUrl(PRODUCT_ENDPOINTS.create), getById: (id: number) => buildApiUrl(PRODUCT_ENDPOINTS.getById(id)), update: (id: number) => buildApiUrl(PRODUCT_ENDPOINTS.update(id)), delete: (id: number) => buildApiUrl(PRODUCT_ENDPOINTS.delete(id)), permanentDelete: (id: number) => buildApiUrl(PRODUCT_ENDPOINTS.permanentDelete(id)), restore: (id: number) => buildApiUrl(PRODUCT_ENDPOINTS.restore(id)) },
  orders: { current: () => buildApiUrl(ORDER_ENDPOINTS.current), list: () => buildApiUrl(ORDER_ENDPOINTS.list), getById: (id: number) => buildApiUrl(ORDER_ENDPOINTS.getById(id)), create: () => buildApiUrl(ORDER_ENDPOINTS.create), addItem: (orderId: number) => buildApiUrl(ORDER_ENDPOINTS.addItem(orderId)), updateItem: (itemId: number) => buildApiUrl(ORDER_ENDPOINTS.updateItem(itemId)), deleteItem: (itemId: number) => buildApiUrl(ORDER_ENDPOINTS.deleteItem(itemId)), complete: (orderId: number) => buildApiUrl(ORDER_ENDPOINTS.complete(orderId)) },
  discounts: { create: () => buildApiUrl(DISCOUNT_ENDPOINTS.create), list: () => buildApiUrl(DISCOUNT_ENDPOINTS.list), deleted: () => buildApiUrl(DISCOUNT_ENDPOINTS.deleted), getById: (id: number) => buildApiUrl(DISCOUNT_ENDPOINTS.getById(id)), update: (id: number) => buildApiUrl(DISCOUNT_ENDPOINTS.update(id)), delete: (id: number) => buildApiUrl(DISCOUNT_ENDPOINTS.delete(id)) }
} as const;
